module.exports = {
  apps: [
    {
      name: 'devforgeai-backend',
      script: 'venv\\Scripts\\python.exe',
      args: '-m uvicorn app.main:app --host 0.0.0.0 --port 19000 --reload',
      cwd: './backend',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      restart_delay: 2000,
      max_restarts: 10,
      windowsHide: true,
      env: {
        PYTHONUNBUFFERED: '1',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '../logs/backend-error.log',
      out_file: '../logs/backend-out.log',
      merge_logs: true,
    },
    {
      name: 'devforgeai-frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev -p 3001',
      cwd: './frontend',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      restart_delay: 2000,
      max_restarts: 10,
      windowsHide: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '../logs/frontend-error.log',
      out_file: '../logs/frontend-out.log',
      merge_logs: true,
    },
  ],
}
