"""Live Development Workbench — SSE streaming + agent intervention."""

import uuid
import json
import asyncio
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List, AsyncGenerator
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.middleware.auth import verify_api_key
from fastapi import Depends

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/v1/workbench", tags=["workbench"])

# ─── In-memory session store ──────────────────────────────────────────────────
_sessions: Dict[str, Dict[str, Any]] = {}
_queues:   Dict[str, asyncio.Queue] = {}


# ─── Models ───────────────────────────────────────────────────────────────────
class WorkbenchCreate(BaseModel):
    task: str
    agent_type: str = "coder"
    model: Optional[str] = None
    project_path: Optional[str] = None


class WorkbenchMessage(BaseModel):
    message: str


class WorkbenchEvent(BaseModel):
    type: str        # file_created | file_modified | agent_thought | tool_call | error | waiting | done | user_message | info
    payload: Dict[str, Any]
    ts: str


# ─── Helpers ──────────────────────────────────────────────────────────────────
def _evt(session_id: str, type: str, **payload) -> WorkbenchEvent:
    return WorkbenchEvent(type=type, payload=payload, ts=datetime.utcnow().isoformat())


def _push(session_id: str, type: str, **payload):
    """Push an event into a session's queue (non-blocking)."""
    if session_id in _queues:
        evt = _evt(session_id, type, **payload)
        try:
            _queues[session_id].put_nowait(evt.model_dump())
        except asyncio.QueueFull:
            pass


async def _mock_agent_run(session_id: str, task: str, agent_type: str, model: str):
    """
    Simulated agent execution loop.
    In production this would invoke GLM-5/Codex/Claude Code and stream real events.
    The structure and event protocol is identical — just replace the mock steps.
    """
    session = _sessions.get(session_id)
    if not session:
        return

    session["status"] = "running"
    session["started_at"] = datetime.utcnow().isoformat()

    steps = [
        ("info",         {"message": f"Starting {agent_type} agent for: {task}"}),
        ("agent_thought",{"thought": f"Analyzing task requirements: {task}"}),
        ("agent_thought",{"thought": "Planning implementation approach..."}),
        ("tool_call",    {"tool": "read_file", "args": {"path": "README.md"}, "result": "Project context loaded"}),
        ("file_created", {"path": "src/feature.py", "content": "# Generated by DevForgeAI\n\ndef main():\n    pass\n"}),
        ("agent_thought",{"thought": "Writing implementation..."}),
        ("file_modified",{"path": "src/feature.py", "diff": "+def process(data):\n+    return data\n"}),
        ("tool_call",    {"tool": "run_tests", "args": {}, "result": "All tests passed ✓"}),
        ("file_modified",{"path": "requirements.txt", "diff": "+fastapi>=0.100\n"}),
        ("agent_thought",{"thought": "Task complete. Reviewing output..."}),
        ("done",         {"message": "Task completed successfully.", "files_changed": ["src/feature.py", "requirements.txt"]}),
    ]

    for event_type, payload in steps:
        if _sessions.get(session_id, {}).get("status") == "cancelled":
            _push(session_id, "info", message="Session cancelled by user.")
            break

        # Check for pending user messages
        pending = session.get("pending_messages", [])
        if pending:
            for msg in pending:
                _push(session_id, "user_message", message=msg, handled=True)
                _push(session_id, "agent_thought", thought=f"Incorporating user input: {msg}")
            session["pending_messages"] = []

        _push(session_id, event_type, **payload)

        if event_type == "file_created" or event_type == "file_modified":
            session.setdefault("files", [])
            path = payload.get("path", "")
            if path not in session["files"]:
                session["files"].append(path)

        await asyncio.sleep(1.5)

    if session.get("status") == "running":
        session["status"] = "completed"
        session["completed_at"] = datetime.utcnow().isoformat()

    _push(session_id, "done", message="Session ended.", status=session["status"])


# ─── Routes ───────────────────────────────────────────────────────────────────
@router.post("/sessions", dependencies=[Depends(verify_api_key)])
async def create_session(body: WorkbenchCreate):
    """Start a new workbench session."""
    session_id = str(uuid.uuid4())
    model = body.model or "ollama/glm4:latest"

    _sessions[session_id] = {
        "id": session_id,
        "task": body.task,
        "agent_type": body.agent_type,
        "model": model,
        "project_path": body.project_path,
        "status": "pending",
        "created_at": datetime.utcnow().isoformat(),
        "started_at": None,
        "completed_at": None,
        "files": [],
        "pending_messages": [],
    }
    _queues[session_id] = asyncio.Queue(maxsize=500)

    # Kick off the agent in the background
    asyncio.create_task(_mock_agent_run(session_id, body.task, body.agent_type, model))

    return _sessions[session_id]


@router.get("/sessions", dependencies=[Depends(verify_api_key)])
async def list_sessions():
    return {"data": list(_sessions.values()), "total": len(_sessions)}


@router.get("/sessions/{session_id}", dependencies=[Depends(verify_api_key)])
async def get_session(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    return _sessions[session_id]


@router.get("/sessions/{session_id}/stream")
async def stream_session(session_id: str, request: Request):
    """SSE stream of workbench events. No auth header required for EventSource."""
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found")

    async def event_generator() -> AsyncGenerator[str, None]:
        queue = _queues.get(session_id)
        if not queue:
            yield f"data: {json.dumps({'type': 'error', 'payload': {'message': 'Session queue not found'}})}\n\n"
            return

        # Send current session state as first event
        yield f"data: {json.dumps({'type': 'init', 'payload': _sessions[session_id]})}\n\n"

        while True:
            if await request.is_disconnected():
                break
            try:
                evt = await asyncio.wait_for(queue.get(), timeout=15.0)
                yield f"data: {json.dumps(evt)}\n\n"
                if evt.get("type") == "done" and _sessions.get(session_id, {}).get("status") != "running":
                    break
            except asyncio.TimeoutError:
                yield f"data: {json.dumps({'type': 'ping', 'payload': {}})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Access-Control-Allow-Origin": "*",
        }
    )


@router.post("/sessions/{session_id}/message", dependencies=[Depends(verify_api_key)])
async def send_message(session_id: str, body: WorkbenchMessage):
    """Inject a user message into the running agent."""
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    session = _sessions[session_id]
    session.setdefault("pending_messages", []).append(body.message)
    _push(session_id, "user_message", message=body.message, handled=False)
    return {"ok": True}


@router.post("/sessions/{session_id}/cancel", dependencies=[Depends(verify_api_key)])
async def cancel_session(session_id: str):
    if session_id not in _sessions:
        raise HTTPException(status_code=404, detail="Session not found")
    _sessions[session_id]["status"] = "cancelled"
    _push(session_id, "info", message="Cancelling session...")
    return {"ok": True}


@router.delete("/sessions/{session_id}", dependencies=[Depends(verify_api_key)])
async def delete_session(session_id: str):
    _sessions.pop(session_id, None)
    _queues.pop(session_id, None)
    return {"ok": True}
